set(_CATKIN_CURRENT_PACKAGE "ur5_head_description")
set(ur5_head_description_VERSION "0.0.0")
set(ur5_head_description_MAINTAINER "ericwu <ericwu@todo.todo>")
set(ur5_head_description_PACKAGE_FORMAT "2")
set(ur5_head_description_BUILD_DEPENDS "controller_manager" "gazebo_ros" "joint_state_publisher" "robot_state_publisher" "rospy" "rviz")
set(ur5_head_description_BUILD_EXPORT_DEPENDS "controller_manager" "gazebo_ros" "joint_state_publisher" "robot_state_publisher" "rospy" "rviz")
set(ur5_head_description_BUILDTOOL_DEPENDS "catkin")
set(ur5_head_description_BUILDTOOL_EXPORT_DEPENDS )
set(ur5_head_description_EXEC_DEPENDS "controller_manager" "gazebo_ros" "joint_state_publisher" "robot_state_publisher" "rospy" "rviz")
set(ur5_head_description_RUN_DEPENDS "controller_manager" "gazebo_ros" "joint_state_publisher" "robot_state_publisher" "rospy" "rviz")
set(ur5_head_description_TEST_DEPENDS )
set(ur5_head_description_DOC_DEPENDS )
set(ur5_head_description_URL_WEBSITE "")
set(ur5_head_description_URL_BUGTRACKER "")
set(ur5_head_description_URL_REPOSITORY "")
set(ur5_head_description_DEPRECATED "")